import os

CLIENT_ID = os.environ.get('SPOTIPY_CLIENT_ID', '<YOUR SPOTIFY_CLIENT_ID HERE>')
CLIENT_SECRET = os.environ.get('SPOTIPY_CLIENT_SECRET', '<YOUR CLIENT_SECRET HERE>')
REDIRECT_URI = os.environ.get('SPOTIPY_REDIRECT_URI', '<YOUR REDIRECT_URI HERE>')
